version: '3.7'

services:
  demo.producer:
    image: ${DOCKER_REGISTRY-}demo.producer
    build:
      context: .
      dockerfile: src/Demo.Producer/Dockerfile

  demo.consumer:
    image: ${DOCKER_REGISTRY-}demo.consumer
    build:
      context: .
      dockerfile: src/Demo.Consumer/Dockerfile

  demo.kcl.consumer:
    image: ${DOCKER_REGISTRY-}demo.kcl.consumer
    build:
      context: .
      dockerfile: src/Demo.Kcl.Consumer/Dockerfile
